// expected exit code is 1

Null foo(Integer value) { }

foo(1, 2);