// expected exit code is 4

Null test(Integer... args) {
  exit(len(args));
}
test(1, 2, 3, 4);
